### ISSUE TITLE
md2slides doesn't reload presentation

### ISSUE THREAD

**Issue by ipedrazas** [agonzalezro/md2slides#1]
If you modify the md file while running `md2slides -d` the presentation is not updated.

I've made a simple test by adding a log that prints the number of slides:

```
        r.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
            ifErrFatal(p.Write(w))
            p.Reload()
            log.Println("Reload", len(p.Slides))
        })
```

And the number is not updated (I've deleted a couple of slides):

```
-> % md2slides -d distributes-archituctures.md
2015/12/22 06:41:40 Serving slides at :8080
2015/12/22 06:41:47 Reload 14
2015/12/22 06:42:11 Reload 14
```

What I did find is that `p.Reload()` returns an error `invalid argument` (that is ignored)

**Comment by agonzalezro** [comment]
Hi @ipedrazas, thanks for reporting.

I fixed this after thr first release. Could you please install latest
master? It should be working there. Let me know if it isn't.

**Comment by ipedrazas** [comment]
It is not. I've forked it and build from source.

**Comment by agonzalezro** [comment]
Sorry about the late response, but this is fixed now on https://github.com/agonzalezro/md2slides/releases/tag/v0.5

Thanks for the heads up!
